---
# tasks file for apache_web

- name: 1. Actualizar la lista de repositorios
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: 2. Instalar el paquete Apache2
  apt:
    name: apache2
    state: present

- name: 3. Asegurar que el servicio est√° iniciado
  service:
    name: apache2
    state: started
    enabled: yes
